child_config: .swiftlint_opt_in_rules.yml

included:
  - ./App/
  - ./Modules/

excluded:
  - ./**/.build/

disabled_rules:
  - force_cast
  - force_try
  - force_unwrapping

  - closure_body_length
  - file_length
  - function_body_length
  - generic_type_name
  - identifier_name
  - line_length
  - type_body_length
  - type_name

trailing_comma:
  mandatory_comma: true

cyclomatic_complexity:
  ignores_case_statements: true
