opt_in_rules:
# - accessibility_label_for_image            # lint
  - accessibility_trait_for_button           # lint
# - anonymous_argument_in_multiline_closure  # idiomatic
# - anyobject_protocol                       # lint
  - array_init                               # lint
  - attributes                               # style
# - balanced_xctest_lifecycle                # lint
# - closure_body_length                      # metrics
  - closure_end_indentation                  # style
  - closure_spacing                          # style
  - collection_alignment                     # style
  - comma_inheritance                        # style
# - conditional_returns_on_newline           # style
  - contains_over_filter_count               # performance
  - contains_over_filter_is_empty            # performance
  - contains_over_first_not_nil              # performance
  - contains_over_range_nil_comparison       # performance
  - convenience_type                         # idiomatic
  - direct_return                            # style
  - discarded_notification_center_observer   # lint
  - discouraged_assert                       # idiomatic
  - discouraged_none_name                    # idiomatic
# - discouraged_object_literal               # idiomatic
  - discouraged_optional_boolean             # idiomatic
# - discouraged_optional_collection          # idiomatic
  - empty_collection_literal                 # performance
  - empty_count                              # performance
  - empty_string                             # performance
  - empty_xctest_method                      # lint
  - enum_case_associated_values_count        # metrics
  - expiring_todo                            # lint
# - explicit_acl                             # idiomatic
# - explicit_enum_raw_value                  # idiomatic
  - explicit_init                            # idiomatic
# - explicit_top_level_acl                   # idiomatic
# - explicit_type_interface                  # idiomatic
# - extension_access_modifier                # idiomatic
  - fallthrough                              # idiomatic
# - fatal_error_message                      # idiomatic
# - file_header                              # style
# - file_name                                # idiomatic
  - file_name_no_space                       # idiomatic
# - file_types_order                         # style
  - first_where                              # performance
  - flatmap_over_map_reduce                  # performance
# - force_unwrapping                         # idiomatic
  - function_default_parameter_at_end        # idiomatic
  - ibinspectable_in_extension               # lint
  - identical_operands                       # lint
  - implicit_return                          # style
# - implicitly_unwrapped_optional            # idiomatic
# - indentation_width                        # style
# - inert_defer                              # lint
  - joined_default_parameter                 # idiomatic
  - last_where                               # performance
  - legacy_multiple                          # idiomatic
  - legacy_objc_type                         # idiomatic
  - let_var_whitespace                       # style
  - literal_expression_end_indentation       # style
  - local_doc_comment                        # lint
  - lower_acl_than_parent                    # lint
# - missing_docs                             # lint
  - modifier_order                           # style
  - multiline_arguments                      # style
# - multiline_arguments_brackets             # style
  - multiline_function_chains                # style
  - multiline_literal_brackets               # style
  - multiline_parameters                     # style
# - multiline_parameters_brackets            # style
  - nimble_operator                          # idiomatic
# - no_extension_access_modifier             # idiomatic
# - no_grouping_extension                    # idiomatic
# - no_magic_numbers                         # idiomatic
# - non_overridable_class_declaration        # style
  - nslocalizedstring_key                    # lint
  - nslocalizedstring_require_bundle         # lint
  - number_separator                         # style
# - object_literal                           # idiomatic
  - operator_usage_whitespace                # style
  - optional_enum_case_matching              # style
  - overridden_super_call                    # lint
  - override_in_extension                    # lint
  - pattern_matching_keywords                # idiomatic
  - period_spacing                           # style
# - prefer_nimble                            # idiomatic
  - prefer_self_in_static_references         # style
  - prefer_self_type_over_type_of_self       # style
  - prefer_zero_over_explicit_init           # idiomatic
# - prefixed_toplevel_constant               # style
  - private_action                           # lint
  - private_outlet                           # lint
  - private_subject                          # lint
# - private_swiftui_state                    # lint
# - prohibited_interface_builder             # lint
  - prohibited_super_call                    # lint
  - quick_discouraged_call                   # lint
  - quick_discouraged_focused_test           # lint
  - quick_discouraged_pending_test           # lint
  - raw_value_for_camel_cased_codable_enum   # lint
  - reduce_into                              # performance
  - redundant_nil_coalescing                 # idiomatic
  - redundant_self_in_closure                # style
  - redundant_type_annotation                # idiomatic
# - required_deinit                          # lint
# - required_enum_case                       # lint
  - return_value_from_void_function          # idiomatic
  - self_binding                             # style
  - shorthand_optional_binding               # idiomatic
  - single_test_class                        # style
# - sorted_enum_cases                        # style
  - sorted_first_last                        # performance
  - sorted_imports                           # style
  - static_operator                          # idiomatic
# - strict_fileprivate                       # idiomatic
# - strong_iboutlet                          # lint
  - superfluous_else                         # style
# - switch_case_on_newline                   # style
  - test_case_accessibility                  # lint
  - toggle_bool                              # idiomatic
# - trailing_closure                         # style
# - type_contents_order                      # style
  - unavailable_function                     # idiomatic
  - unhandled_throwing_task                  # lint
  - unneeded_parentheses_in_closure_argument # style
# - unowned_variable_capture                 # lint
  - untyped_error_in_catch                   # idiomatic
# - unused_capture_list                      # lint
  - vertical_parameter_alignment_on_call     # style
# - vertical_whitespace_between_cases        # style
  - vertical_whitespace_closing_braces       # style
  - vertical_whitespace_opening_braces       # style
# - weak_delegate                            # lint
# - xct_specific_matcher                     # idiomatic
  - yoda_condition                           # lint
