child_config: .swiftlint_opt_in_rules.yml

included:
  - ./App/
  - ./Modules/

excluded:
  - ./*/.build/

disabled_rules:
  - force_cast
  - force_try
  - file_length
  - function_body_length
  - line_length
  - type_body_length

identifier_name:
  min_length:
    warning: 1
  allowed_symbols: [_]
  validates_start_with_lowercase: false

trailing_comma:
  mandatory_comma: true

cyclomatic_complexity:
  ignores_case_statements: true
