name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy-make-target: deploy-Staging
    secrets:
      slack-url: ${{ secrets.SLACK_URL }}
      distribution-certificate-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
      distribution-certificate-password: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
      keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      apple-id: ${{ secrets.APPLE_ID }}
      itc-team-id: ${{ secrets.ITC_TEAM_ID }}
      team-id: ${{ secrets.TEAM_ID }}
      fastlane-apple-application-specific-password: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      app-store-connect-api-key-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      app-store-connect-api-key-issuer-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      app-store-connect-api-key-key: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy-make-target: deploy-Production
    secrets:
      slack-url: ${{ secrets.SLACK_URL }}
      distribution-certificate-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
      distribution-certificate-password: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
      keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      apple-id: ${{ secrets.APPLE_ID }}
      itc-team-id: ${{ secrets.ITC_TEAM_ID }}
      team-id: ${{ secrets.TEAM_ID }}
      fastlane-apple-application-specific-password: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      app-store-connect-api-key-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      app-store-connect-api-key-issuer-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      app-store-connect-api-key-key: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
