name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}

  check:
    runs-on: macos-12
    timeout-minutes: 30
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Check
        run: make check

      - name: Report Coverage
        run: make report_coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
