name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        # workaround for https://github.com/norio-nomura/action-swiftlint/issues/43
        # env:
        #   DIFF_BASE: ${{ github.base_ref }}

  check:
    runs-on: macos-13
    timeout-minutes: 30
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Check
        run: make check
        env:
          LICENSE_PLIST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Codecov
        uses: codecov/codecov-action@v3.1.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          xcode: true
          xcode_archive_path: ./fastlane/test_output/ios-app-template.stg.xcresult
