name: Renovate

on:
  push:
    branches:
      - 'renovate/**'
    paths:
      - '**/Package.swift'

jobs:
  resolve_package_dependencies:
    runs-on: macos-14
    timeout-minutes: 30
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Resolve Package Dependencies
        run: make resolve_package_dependencies

      - name: Diff
        id: diff
        run: git diff --exit-code **/Package.resolved
        continue-on-error: true

      - name: Commit and Push
        if: ${{ steps.diff.outcome == 'failure' }}
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add **/Package.resolved
          git commit --author=. -m 'chore(deps): resolve package dependencies'
          git push
